Combination
OirthirSAT/image-processing-pipeline pull request #18
Opened 2024-10-28 17:58 UTC by lewismcnish

## Overview

(**Why** you made the changes and **What** they achieved)

## Changes

- ...
- ...
- ...

## Testing

(**How** you tested it and **proof** it works)

## Additional Information

(**Extra Notes** / **Known Issues** / **Discussion Points** / **Request Feedback**)

2024-10-28 18:07 UTC, CameronFraserr requested changes
Overall looks good, just a few minor tweaks

2024-10-28 18:07 UTC, CameronFraserr commented on cloud-mask/cloud-mask.ipynb
> +   "display_name": "Python 3",
Why Python?

2024-10-28 18:07 UTC, CameronFraserr commented on cloud-mask/cloud-mask.ipynb
> +  "orig_nbformat": 4
Why 4? Is this a magic number?

2024-11-04 21:16 UTC, JazzyMaxine commented
This PR was created as a demonstration IIUC. I'll close it but if I'm mistaken feel free to reopen.

2024-11-04 21:16 UTC, closed without merging